import { ModeToggle } from "@/components/ModeToggle";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div>
          <ModeToggle />
          <h1 className=" font-bold text-2xl  underline">jhgdhjgh</h1>
        </div>
      </>
    </>
  );
}
